name: Continuous build using OMV

on:
  push:
    branches: [ main, development, experimental, test*, feat/* ]
  pull_request:
    branches: [ main, development, experimental, test*, feat/* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
          #engine: [ jNeuroML_validate, "NEURON:7.6", "NEURON:8.0", jNeuroML_NEURON, jNeuroML_NetPyNE, jNeuroML_EDEN ]
        engine: [ jNeuroML_validate, "NEURON:7.6", "NEURON:8.0", jNeuroML_NEURON, jNeuroML_EDEN]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        pip install scipy sympy matplotlib cython pandas tables

        pip install 'numpy<=1.23.0' # see https://github.com/OpenSourceBrain/osb-model-validation/issues/91

    - name: Compile some mod files, required for NEURON tests
      run: |
        if [[  ${{ matrix.engine }} == *"NEURON"* ]]; then omv install NEURON; cd NeuroML/HumanCell/NEURON-test ; nrnivmodl ../../../HumanCell/; fi

    - name: Run OMV tests on engine ${{ matrix.engine }}
      run: |
        omv all -V --engine=${{ matrix.engine }}

    - name: OMV final version info
      run: |
        omv list -V # list installed engines
        env
